version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-buster
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Checkstyle
          command: mvn checkstyle:checkstyle

      - run:
          name: Unit & Integration Tests
          command: mvn verify

      - run:
          name: Static Analysis
          command: mvn sonar:sonar

  deploy:
    docker:
      - image: circleci/openjdk:11-jdk-buster
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            if [[ $(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec) =~ .*"SNAPSHOT" ]]
            then
              echo "SNAPSHOT version will not be automatically deployed"
            else
              mvn -s .circleci/settings.xml -DskipTests deploy
            fi

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master